### ISSUE TITLE
Help Needed !!!!

### ISSUE THREAD

**Issue by TheProest35YT** [ProestCorp/ProestMine#1]
@keithkfng , @remotevase @Ad5001 @Taki21 Help Pls

**Comment by remotevase** [comment]
No. I will not help on yet another mine software

**Comment by keithkfng** [comment]
I will not be helping out. Instead of creating 100+ new pieces of software for MCPE servers, why don't just contribute to PocketMine?

**Comment by Ad5001** [comment]
PR not merged sooo...

**Comment by TheProest35YT** [comment]
PM is very Inactive

**Comment by keithkfng** [comment]
That doesn't mean you shouldn't help out.

**Comment by Taki21** [comment]
As @keithkfng says we dont need too much replicas of PocketMine, its getting out of hand. Because of ImagicalMine, why does everybody decide to start making more mine software? We woudnt be here for PocketMine, we wouldn,t have allies with each other or no each other or talk to each other if it were for PocketMine, also as @keithkfng said, just contribute to PocketMine, just because its inactive, doesnt  mean the owner wouldnt merge PRs, also contributors are there beside the Owner to help out.

**Comment by keithkfng** [comment]
If you wanted to know how ImagicalMine started, it was actually just a fork of PocketMine, edited to be compatible with 0.13 so other server owners could use(because the PM devs were inactive and didn't update it as fast we did). It was never intended to encourage projects like Genisys to become open-source or ClearSky to be forked from ImagicalMine.

**Comment by TheProest35YT** [comment]
So You mean genisys and clearsky copied codes from ImagicalMine ?

**Comment by Ad5001** [comment]
Yeah

**Comment by keithkfng** [comment]
Of course they did. And ImagicalMine copied from them too. It's all a frenzy.

**Comment by TheProest35YT** [comment]
You should takedown them like DMCA Takedown

**Comment by TheProest35YT** [comment]
Then @Github will take down
